import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { AuthService } from '../../services/auth';
import { Router } from '@angular/router';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './login.html',
  styleUrls: ['./login.css']
})
export class LoginComponent {
  email = '';
  password = '';
  error = '';
  loading = false;

  constructor(private authService: AuthService, private router: Router) {
    console.log('LoginComponent: Initialized');
  }

  login() {
    this.loading = true;
    this.error = '';
    this.authService.login({ email: this.email, password: this.password }).subscribe({
      next: () => {
        this.loading = false;
        this.router.navigate(['/dashboard']);
      },
      error: (err) => {
        this.error = 'Invalid credentials';
        this.loading = false;
      }
    });
  }

  openTestReports() {
    const message = `Test Coverage Reports:

Backend Tests:
http://localhost:3000/coverage/

API Documentation (Swagger):
http://localhost:3000/api

Note: Backend tests report shows the HTML coverage report generated by Jest.
Swagger provides interactive API documentation.`;

    alert(message);

    // Open backend coverage in new tab
    window.open('http://localhost:3000/coverage/', '_blank');
  }
}
